"""Build 04_comparison.ipynb — FINDHasher_optimized vs dHash comprehensive comparison."""
import json

def code(src): return {"cell_type":"code","execution_count":None,"metadata":{},"outputs":[],"source":src if isinstance(src,list) else [src]}
def md(src):   return {"cell_type":"markdown","metadata":{},"source":src if isinstance(src,list) else [src]}

cells = []

# ── 0  Title ───────────────────────────────────────────────────────────────────
cells.append(md([
    "# Part 2 — FINDHasher_optimized vs dHash: Comprehensive Comparison\n",
    "\n",
    "This notebook provides a full side-by-side evaluation of `FINDHasher_optimized` against `dHash` (`hash_size=16`, 256-bit) across three axes:\n",
    "\n",
    "1. **Accuracy** — distance distributions, ROC/AUC, PR/AUC, EER, Precision/Recall/F1, robustness to transformations\n",
    "2. **Runtime** — wall-clock and CPU time per image\n",
    "3. **Memory** — peak memory per image and scaling behaviour\n",
]))

# ── 1  Setup ───────────────────────────────────────────────────────────────────
cells.append(md("---\n## 0. Setup"))
cells.append(code([
    "import sys\n",
    "import io\n",
    "import timeit\n",
    "import tracemalloc\n",
    "import time\n",
    "import random\n",
    "from pathlib import Path\n",
    "from collections import defaultdict\n",
    "\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "import imagehash\n",
    "from PIL import Image, ImageFilter, ImageEnhance\n",
    "from sklearn.metrics import (\n",
    "    roc_curve, roc_auc_score,\n",
    "    precision_recall_curve, average_precision_score\n",
    ")\n",
    "\n",
    "sys.path.insert(0, str(Path('../').resolve()))\n",
    "from FINd_optimized import FINDHasher_optimized\n",
    "\n",
    "random.seed(42)\n",
    "np.random.seed(42)\n",
    "\n",
    "find_hasher = FINDHasher_optimized()\n",
    "\n",
    "def dhash_fn(img_path):\n",
    "    \"\"\"dHash hash_size=16 → 256-bit hash, matches FINd output size.\"\"\"\n",
    "    return imagehash.dhash(Image.open(img_path), hash_size=16)\n",
    "\n",
    "def dhash_from_image(img):\n",
    "    return imagehash.dhash(img, hash_size=16)\n",
    "\n",
    "MEME_DIR   = Path('/Users/noha/Desktop/Hilary_term /DS in practice TA/Summative /meme_images')\n",
    "OUTPUT_DIR = Path('../output')\n",
    "OUTPUT_DIR.mkdir(exist_ok=True)\n",
    "assert MEME_DIR.exists()\n",
    "\n",
    "all_images = sorted(MEME_DIR.glob('*.jpg'))\n",
    "\n",
    "family_map = defaultdict(list)\n",
    "for p in all_images:\n",
    "    family_map[p.name.split('_')[0]].append(p)\n",
    "\n",
    "HASHERS = {'FINDHasher_optimized': find_hasher.fromFile, 'dHash (16×16)': dhash_fn}\n",
    "COLORS  = {'FINDHasher_optimized': 'steelblue', 'dHash (16×16)': 'darkorange'}\n",
    "\n",
    "print(f'Total images   : {len(all_images):,}')\n",
    "print(f'Total families : {len(family_map):,}')\n",
    "print(f'dHash bits     : {len(dhash_fn(all_images[0]).hash.flatten())}')\n",
    "print('Setup complete.')\n",
]))

# ── 2  Algorithm overview ──────────────────────────────────────────────────────
cells.append(md([
    "---\n## 1. Algorithm Overview\n",
    "\n",
    "| Property | FINDHasher_optimized | dHash (16×16) |\n",
    "|---|---|---|\n",
    "| Hash size | 256 bits (16×16 DCT) | 256 bits (16×16 pixel diff) |\n",
    "| Core idea | DCT frequency vs median threshold | Adjacent pixel brightness differences |\n",
    "| Colour handling | RGB → luminance (ITU-R BT.601) | Greyscale (`L` mode) |\n",
    "| Pre-processing | Box filter (local mean smoothing) | Resize to 17×16 |\n",
    "| Distance metric | Hamming distance | Hamming distance |\n",
    "\n",
    "Both produce 256-bit hashes — all distance comparisons are on the same 0–256 scale.\n",
]))

# ── 3  Build pairs ─────────────────────────────────────────────────────────────
cells.append(md("---\n## 2. Accuracy Evaluation\n\n### 2a — Build Evaluation Pairs"))
cells.append(code([
    "N_PAIRS = 500\n",
    "random.seed(42)\n",
    "\n",
    "eligible = [f for f, imgs in family_map.items() if len(imgs) >= 2]\n",
    "fids     = list(family_map.keys())\n",
    "\n",
    "same_pairs = []\n",
    "while len(same_pairs) < N_PAIRS:\n",
    "    fam = random.choice(eligible)\n",
    "    p1, p2 = random.sample(family_map[fam], 2)\n",
    "    same_pairs.append((p1, p2))\n",
    "\n",
    "diff_pairs = []\n",
    "while len(diff_pairs) < N_PAIRS:\n",
    "    f1, f2 = random.sample(fids, 2)\n",
    "    p1 = random.choice(family_map[f1])\n",
    "    p2 = random.choice(family_map[f2])\n",
    "    diff_pairs.append((p1, p2))\n",
    "\n",
    "print(f'Same-family pairs     : {len(same_pairs)}')\n",
    "print(f'Different-family pairs: {len(diff_pairs)}')\n",
]))

# ── 4  Compute distances ───────────────────────────────────────────────────────
cells.append(md("### 2b — Compute Hamming Distances"))
cells.append(code([
    "print('Computing FINd distances...')\n",
    "find_same  = [find_hasher.fromFile(str(p1)) - find_hasher.fromFile(str(p2)) for p1,p2 in same_pairs]\n",
    "find_diff  = [find_hasher.fromFile(str(p1)) - find_hasher.fromFile(str(p2)) for p1,p2 in diff_pairs]\n",
    "\n",
    "print('Computing dHash distances...')\n",
    "dhash_same = [dhash_fn(p1) - dhash_fn(p2) for p1,p2 in same_pairs]\n",
    "dhash_diff = [dhash_fn(p1) - dhash_fn(p2) for p1,p2 in diff_pairs]\n",
    "\n",
    "print('\\nFINd  | same mean: {:.1f}  diff mean: {:.1f}'.format(np.mean(find_same), np.mean(find_diff)))\n",
    "print('dHash | same mean: {:.1f}  diff mean: {:.1f}'.format(np.mean(dhash_same), np.mean(dhash_diff)))\n",
]))

# ── 5  Distance distributions ──────────────────────────────────────────────────
cells.append(md("### 2c — Hamming Distance Distributions"))
cells.append(code([
    "fig, axes = plt.subplots(2, 2, figsize=(14, 10))\n",
    "\n",
    "for col, (name, s_d, d_d) in enumerate([\n",
    "    ('FINDHasher_optimized', find_same, find_diff),\n",
    "    ('dHash (16×16)',        dhash_same, dhash_diff),\n",
    "]):\n",
    "    s_mean, d_mean = np.mean(s_d), np.mean(d_d)\n",
    "\n",
    "    # Histogram\n",
    "    ax = axes[0, col]\n",
    "    ax.hist(s_d, bins=30, alpha=0.75, color='steelblue', edgecolor='white', lw=0.5,\n",
    "            label=f'Same-family  (mean={s_mean:.0f})')\n",
    "    ax.hist(d_d, bins=30, alpha=0.75, color='coral',     edgecolor='white', lw=0.5,\n",
    "            label=f'Diff-family  (mean={d_mean:.0f})')\n",
    "    ax.axvline(s_mean, color='steelblue', ls='--', lw=1.5)\n",
    "    ax.axvline(d_mean, color='coral',     ls='--', lw=1.5)\n",
    "    y_top = ax.get_ylim()[1]\n",
    "    ax.annotate('', xy=(d_mean, y_top*0.12), xytext=(s_mean, y_top*0.12),\n",
    "                arrowprops=dict(arrowstyle='<->', color='black', lw=1.5))\n",
    "    ax.text((s_mean+d_mean)/2, y_top*0.15, f'gap={d_mean-s_mean:.0f}',\n",
    "            ha='center', fontsize=9)\n",
    "    ax.set_title(f'{name} — Distance Histogram', fontweight='bold')\n",
    "    ax.set_xlabel('Hamming Distance')\n",
    "    ax.set_ylabel('Count')\n",
    "    ax.legend(fontsize=9)\n",
    "\n",
    "    # Box plot\n",
    "    ax2 = axes[1, col]\n",
    "    bp = ax2.boxplot([s_d, d_d], patch_artist=True,\n",
    "                     labels=['Same family', 'Diff family'],\n",
    "                     widths=0.5, medianprops=dict(color='black', lw=2))\n",
    "    for patch, c in zip(bp['boxes'], ['steelblue', 'coral']):\n",
    "        patch.set_facecolor(c); patch.set_alpha(0.75)\n",
    "    ax2.set_ylabel('Hamming Distance')\n",
    "    ax2.set_title(f'{name} — Box Plot', fontweight='bold')\n",
    "    ax2.set_facecolor('#f9f9f9')\n",
    "\n",
    "fig.suptitle('Hamming Distance Distributions: Same-family vs Different-family Pairs',\n",
    "             fontsize=13, fontweight='bold')\n",
    "plt.tight_layout()\n",
    "plt.savefig(OUTPUT_DIR / '04_distributions.png', dpi=150, bbox_inches='tight')\n",
    "plt.show()\n",
]))

# ── 6  ROC + AUC ──────────────────────────────────────────────────────────────
cells.append(md([
    "### 2d — ROC Curve and AUC\n",
    "\n",
    "A *positive* prediction is `distance < threshold`. We use `256 − distance` as the similarity score "
    "so that higher scores correspond to more likely duplicates, matching the sklearn convention.\n",
]))
cells.append(code([
    "labels = np.array([1]*N_PAIRS + [0]*N_PAIRS)\n",
    "\n",
    "find_scores  = np.array([256-d for d in find_same]  + [256-d for d in find_diff])\n",
    "dhash_scores = np.array([256-d for d in dhash_same] + [256-d for d in dhash_diff])\n",
    "\n",
    "find_fpr,  find_tpr,  _  = roc_curve(labels, find_scores)\n",
    "dhash_fpr, dhash_tpr, _  = roc_curve(labels, dhash_scores)\n",
    "find_auc  = roc_auc_score(labels, find_scores)\n",
    "dhash_auc = roc_auc_score(labels, dhash_scores)\n",
    "\n",
    "fig, ax = plt.subplots(figsize=(7, 6))\n",
    "ax.plot(find_fpr,  find_tpr,  color='steelblue',  lw=2, label=f'FINDHasher_optimized  AUC={find_auc:.4f}')\n",
    "ax.plot(dhash_fpr, dhash_tpr, color='darkorange', lw=2, label=f'dHash (16×16)          AUC={dhash_auc:.4f}')\n",
    "ax.plot([0,1],[0,1], color='grey', ls='--', lw=1, label='Random classifier')\n",
    "ax.set_xlabel('False Positive Rate', fontsize=11)\n",
    "ax.set_ylabel('True Positive Rate', fontsize=11)\n",
    "ax.set_title('ROC Curve', fontsize=12, fontweight='bold')\n",
    "ax.legend(fontsize=10)\n",
    "ax.grid(alpha=0.3)\n",
    "plt.tight_layout()\n",
    "plt.savefig(OUTPUT_DIR / '04_roc.png', dpi=150, bbox_inches='tight')\n",
    "plt.show()\n",
    "print(f'FINd AUC  : {find_auc:.4f}')\n",
    "print(f'dHash AUC : {dhash_auc:.4f}')\n",
]))

# ── 7  PR curve ────────────────────────────────────────────────────────────────
cells.append(md("### 2e — Precision-Recall Curve and PR-AUC"))
cells.append(code([
    "find_p_curve,  find_r_curve,  _ = precision_recall_curve(labels, find_scores)\n",
    "dhash_p_curve, dhash_r_curve, _ = precision_recall_curve(labels, dhash_scores)\n",
    "find_pr_auc  = average_precision_score(labels, find_scores)\n",
    "dhash_pr_auc = average_precision_score(labels, dhash_scores)\n",
    "\n",
    "fig, ax = plt.subplots(figsize=(7, 6))\n",
    "ax.plot(find_r_curve,  find_p_curve,  color='steelblue',  lw=2, label=f'FINDHasher_optimized  PR-AUC={find_pr_auc:.4f}')\n",
    "ax.plot(dhash_r_curve, dhash_p_curve, color='darkorange', lw=2, label=f'dHash (16×16)          PR-AUC={dhash_pr_auc:.4f}')\n",
    "ax.axhline(0.5, color='grey', ls='--', lw=1, label='Random baseline (0.5)')\n",
    "ax.set_xlabel('Recall', fontsize=11)\n",
    "ax.set_ylabel('Precision', fontsize=11)\n",
    "ax.set_title('Precision-Recall Curve', fontsize=12, fontweight='bold')\n",
    "ax.legend(fontsize=10)\n",
    "ax.grid(alpha=0.3)\n",
    "plt.tight_layout()\n",
    "plt.savefig(OUTPUT_DIR / '04_pr_curve.png', dpi=150, bbox_inches='tight')\n",
    "plt.show()\n",
    "print(f'FINd PR-AUC  : {find_pr_auc:.4f}')\n",
    "print(f'dHash PR-AUC : {dhash_pr_auc:.4f}')\n",
]))

# ── 8  EER ────────────────────────────────────────────────────────────────────
cells.append(md([
    "### 2f — Equal Error Rate (EER)\n",
    "\n",
    "EER is the point where False Positive Rate equals False Negative Rate (1 − TPR). "
    "Lower EER indicates better discriminative power (McKeown & Buchanan, 2023).\n",
]))
cells.append(code([
    "def compute_eer(fpr, tpr):\n",
    "    fnr = 1 - tpr\n",
    "    idx = np.argmin(np.abs(fpr - fnr))\n",
    "    return float((fpr[idx] + fnr[idx]) / 2)\n",
    "\n",
    "find_eer  = compute_eer(find_fpr, find_tpr)\n",
    "dhash_eer = compute_eer(dhash_fpr, dhash_tpr)\n",
    "print(f'FINd EER  : {find_eer:.4f}  ({find_eer*100:.2f}%)')\n",
    "print(f'dHash EER : {dhash_eer:.4f}  ({dhash_eer*100:.2f}%)')\n",
]))

# ── 9  F1 sweep ────────────────────────────────────────────────────────────────
cells.append(md("### 2g — Precision, Recall, F1 Threshold Sweep"))
cells.append(code([
    "def prf1_sweep(same_dists, diff_dists):\n",
    "    thresholds = np.arange(0, 257)\n",
    "    s, d = np.array(same_dists), np.array(diff_dists)\n",
    "    tp = np.array([(s < t).sum() for t in thresholds], dtype=float)\n",
    "    fp = np.array([(d < t).sum() for t in thresholds], dtype=float)\n",
    "    fn = np.array([(s >= t).sum() for t in thresholds], dtype=float)\n",
    "    p  = np.where(tp+fp > 0, tp/(tp+fp), 0.0)\n",
    "    r  = np.where(tp+fn > 0, tp/(tp+fn), 0.0)\n",
    "    f1 = np.where(p+r > 0, 2*p*r/(p+r), 0.0)\n",
    "    return thresholds, p, r, f1\n",
    "\n",
    "find_thr,  find_p,  find_r,  find_f1  = prf1_sweep(find_same,  find_diff)\n",
    "dhash_thr, dhash_p, dhash_r, dhash_f1 = prf1_sweep(dhash_same, dhash_diff)\n",
    "find_best  = np.argmax(find_f1)\n",
    "dhash_best = np.argmax(dhash_f1)\n",
    "\n",
    "fig, axes = plt.subplots(1, 2, figsize=(14, 5))\n",
    "for ax, name, thr, p, r, f1, best in [\n",
    "    (axes[0], 'FINDHasher_optimized', find_thr,  find_p,  find_r,  find_f1,  find_best),\n",
    "    (axes[1], 'dHash (16×16)',        dhash_thr, dhash_p, dhash_r, dhash_f1, dhash_best),\n",
    "]:\n",
    "    ax.plot(thr, p,  color='steelblue',  lw=2, label='Precision')\n",
    "    ax.plot(thr, r,  color='darkorange', lw=2, label='Recall')\n",
    "    ax.plot(thr, f1, color='#2ca02c',    lw=2, label='F1')\n",
    "    ax.axvline(thr[best], color='red', ls='--', lw=1.5,\n",
    "               label=f'Best threshold={thr[best]}  F1={f1[best]:.3f}')\n",
    "    ax.set_title(name, fontweight='bold')\n",
    "    ax.set_xlabel('Hamming distance threshold')\n",
    "    ax.set_ylabel('Score')\n",
    "    ax.set_ylim(0, 1.05)\n",
    "    ax.legend(fontsize=9)\n",
    "    ax.grid(alpha=0.3)\n",
    "\n",
    "fig.suptitle('Precision / Recall / F1 vs Threshold', fontsize=13, fontweight='bold')\n",
    "plt.tight_layout()\n",
    "plt.savefig(OUTPUT_DIR / '04_prf1.png', dpi=150, bbox_inches='tight')\n",
    "plt.show()\n",
    "\n",
    "print(f'FINd  best thr={find_thr[find_best]}   P={find_p[find_best]:.3f}  R={find_r[find_best]:.3f}  F1={find_f1[find_best]:.3f}')\n",
    "print(f'dHash best thr={dhash_thr[dhash_best]}  P={dhash_p[dhash_best]:.3f}  R={dhash_r[dhash_best]:.3f}  F1={dhash_f1[dhash_best]:.3f}')\n",
]))

# ── 10  Robustness comparison ─────────────────────────────────────────────────
cells.append(md([
    "### 2h — Robustness to Image Transformations\n",
    "\n",
    "We apply the same transformation suite as in the FINd evaluation (Notebook 01) "
    "to 10 randomly sampled images and compare mean Hamming distances for both hashers.\n",
]))
cells.append(code([
    "def apply_transforms(img_path):\n",
    "    img = Image.open(img_path).convert('RGB')\n",
    "    t = {}\n",
    "    for q in [90, 70, 50, 30]:\n",
    "        buf = io.BytesIO()\n",
    "        img.save(buf, format='JPEG', quality=q); buf.seek(0)\n",
    "        t[f'JPEG q={q}'] = Image.open(buf).convert('RGB')\n",
    "    w, h = img.size\n",
    "    for scale, label in [(0.75, 'Resize 75%'), (0.5, 'Resize 50%')]:\n",
    "        t[label] = img.resize((int(w*scale), int(h*scale)), Image.LANCZOS)\n",
    "    t['Brightness 50%']  = ImageEnhance.Brightness(img).enhance(0.5)\n",
    "    t['Brightness 150%'] = ImageEnhance.Brightness(img).enhance(1.5)\n",
    "    t['Gaussian blur']   = img.filter(ImageFilter.GaussianBlur(radius=2))\n",
    "    return img, t\n",
    "\n",
    "rob_images = random.sample(all_images, 10)\n",
    "rob_records = []\n",
    "for img_path in rob_images:\n",
    "    orig_img, transforms = apply_transforms(img_path)\n",
    "    h_find_orig  = find_hasher.fromImage(orig_img)\n",
    "    h_dhash_orig = dhash_from_image(orig_img)\n",
    "    for t_name, t_img in transforms.items():\n",
    "        rob_records.append({\n",
    "            'transformation': t_name,\n",
    "            'find_dist':  find_hasher.fromImage(t_img) - h_find_orig,\n",
    "            'dhash_dist': dhash_from_image(t_img) - h_dhash_orig,\n",
    "        })\n",
    "\n",
    "rob_df  = pd.DataFrame(rob_records)\n",
    "rob_sum = rob_df.groupby('transformation').agg(\n",
    "    FINd_mean=('find_dist', 'mean'),\n",
    "    dHash_mean=('dhash_dist', 'mean')\n",
    ").round(2).sort_values('FINd_mean')\n",
    "print(rob_sum.to_string())\n",
]))
cells.append(code([
    "fig, ax = plt.subplots(figsize=(12, 5))\n",
    "x   = np.arange(len(rob_sum))\n",
    "w   = 0.38\n",
    "ax.bar(x - w/2, rob_sum['FINd_mean'],  width=w, color='steelblue',  label='FINDHasher_optimized', alpha=0.85)\n",
    "ax.bar(x + w/2, rob_sum['dHash_mean'], width=w, color='darkorange', label='dHash (16×16)',          alpha=0.85)\n",
    "ax.set_xticks(x)\n",
    "ax.set_xticklabels(rob_sum.index, rotation=20, ha='right')\n",
    "ax.set_ylabel('Mean Hamming Distance')\n",
    "ax.set_title('Robustness to Transformations — Mean Hamming Distance (10 images)',\n",
    "             fontweight='bold')\n",
    "ax.legend()\n",
    "ax.grid(axis='y', alpha=0.3)\n",
    "plt.tight_layout()\n",
    "plt.savefig(OUTPUT_DIR / '04_robustness.png', dpi=150, bbox_inches='tight')\n",
    "plt.show()\n",
]))

# ── 11  Accuracy summary ───────────────────────────────────────────────────────
cells.append(md("### 2i — Accuracy Summary"))
cells.append(code([
    "acc = pd.DataFrame({\n",
    "    'Metric': ['AUC (ROC)', 'PR-AUC', 'EER', 'Best F1',\n",
    "               'Best threshold', 'Same-family mean dist', 'Diff-family mean dist', 'Gap (bits)'],\n",
    "    'FINDHasher_optimized': [\n",
    "        f'{find_auc:.4f}', f'{find_pr_auc:.4f}',\n",
    "        f'{find_eer*100:.2f}%', f'{find_f1[find_best]:.3f}',\n",
    "        str(find_thr[find_best]),\n",
    "        f'{np.mean(find_same):.1f}', f'{np.mean(find_diff):.1f}',\n",
    "        f'{np.mean(find_diff)-np.mean(find_same):.1f}',\n",
    "    ],\n",
    "    'dHash (16×16)': [\n",
    "        f'{dhash_auc:.4f}', f'{dhash_pr_auc:.4f}',\n",
    "        f'{dhash_eer*100:.2f}%', f'{dhash_f1[dhash_best]:.3f}',\n",
    "        str(dhash_thr[dhash_best]),\n",
    "        f'{np.mean(dhash_same):.1f}', f'{np.mean(dhash_diff):.1f}',\n",
    "        f'{np.mean(dhash_diff)-np.mean(dhash_same):.1f}',\n",
    "    ],\n",
    "})\n",
    "acc.set_index('Metric', inplace=True)\n",
    "display(acc)\n",
]))

# ── 12  Runtime ───────────────────────────────────────────────────────────────
cells.append(md("---\n## 3. Runtime Comparison\n\nWall-clock (`timeit.repeat`, min of 10 repeats) and CPU time (`time.process_time`) on 50 images."))
cells.append(code([
    "BENCH = random.sample(all_images, 50)\n",
    "REPS  = 10\n",
    "\n",
    "# Wall-clock\n",
    "find_wall  = timeit.repeat(\n",
    "    stmt='[find_hasher.fromFile(str(p)) for p in BENCH]',\n",
    "    globals={'find_hasher': find_hasher, 'BENCH': BENCH}, repeat=REPS, number=1)\n",
    "dhash_wall = timeit.repeat(\n",
    "    stmt='[dhash_fn(p) for p in BENCH]',\n",
    "    globals={'dhash_fn': dhash_fn, 'BENCH': BENCH}, repeat=REPS, number=1)\n",
    "\n",
    "find_ms  = [(t/len(BENCH))*1000 for t in find_wall]\n",
    "dhash_ms = [(t/len(BENCH))*1000 for t in dhash_wall]\n",
    "\n",
    "# CPU time\n",
    "def cpu_time_per_img(fn, imgs, reps=5):\n",
    "    times = []\n",
    "    for _ in range(reps):\n",
    "        t0 = time.process_time()\n",
    "        for p in imgs: fn(str(p))\n",
    "        times.append((time.process_time() - t0) / len(imgs) * 1000)\n",
    "    return times\n",
    "\n",
    "find_cpu  = cpu_time_per_img(find_hasher.fromFile, BENCH[:20])\n",
    "dhash_cpu = cpu_time_per_img(dhash_fn, BENCH[:20])\n",
    "\n",
    "print(f'FINd  wall-clock : {np.mean(find_ms):.2f} ± {np.std(find_ms):.2f} ms/image')\n",
    "print(f'dHash wall-clock : {np.mean(dhash_ms):.2f} ± {np.std(dhash_ms):.2f} ms/image')\n",
    "print(f'FINd  CPU time   : {np.mean(find_cpu):.2f} ± {np.std(find_cpu):.2f} ms/image')\n",
    "print(f'dHash CPU time   : {np.mean(dhash_cpu):.2f} ± {np.std(dhash_cpu):.2f} ms/image')\n",
]))
cells.append(code([
    "fig, axes = plt.subplots(1, 2, figsize=(12, 5))\n",
    "\n",
    "for ax, title, find_d, dhash_d in [\n",
    "    (axes[0], 'Wall-clock time (ms/image)', find_ms,  dhash_ms),\n",
    "    (axes[1], 'CPU time (ms/image)',         find_cpu, dhash_cpu),\n",
    "]:\n",
    "    means = [np.mean(find_d), np.mean(dhash_d)]\n",
    "    stds  = [np.std(find_d),  np.std(dhash_d)]\n",
    "    bars  = ax.bar(['FINDHasher_optimized', 'dHash (16×16)'],\n",
    "                   means, color=['steelblue', 'darkorange'],\n",
    "                   width=0.45, yerr=stds, capsize=6, edgecolor='white')\n",
    "    for bar, m, s in zip(bars, means, stds):\n",
    "        ax.text(bar.get_x() + bar.get_width()/2, m+s+0.1,\n",
    "                f'{m:.2f} ms', ha='center', va='bottom', fontsize=10)\n",
    "    ax.set_ylabel('ms / image')\n",
    "    ax.set_title(title, fontweight='bold')\n",
    "    ax.grid(axis='y', alpha=0.3)\n",
    "\n",
    "fig.suptitle('Runtime Comparison', fontsize=13, fontweight='bold')\n",
    "plt.tight_layout()\n",
    "plt.savefig(OUTPUT_DIR / '04_runtime.png', dpi=150, bbox_inches='tight')\n",
    "plt.show()\n",
]))

# ── 13  Memory ────────────────────────────────────────────────────────────────
cells.append(md("---\n## 4. Memory Comparison\n\nPeak memory per image using `tracemalloc` (5 repetitions)."))
cells.append(code([
    "TEST_IMG = str(BENCH[0])\n",
    "\n",
    "find_peaks, dhash_peaks = [], []\n",
    "for _ in range(5):\n",
    "    tracemalloc.start()\n",
    "    find_hasher.fromFile(TEST_IMG)\n",
    "    _, peak = tracemalloc.get_traced_memory(); tracemalloc.stop()\n",
    "    find_peaks.append(peak / 1024)\n",
    "\n",
    "    tracemalloc.start()\n",
    "    dhash_fn(TEST_IMG)\n",
    "    _, peak = tracemalloc.get_traced_memory(); tracemalloc.stop()\n",
    "    dhash_peaks.append(peak / 1024)\n",
    "\n",
    "print(f'FINd  peak memory : {np.mean(find_peaks):.0f} KB')\n",
    "print(f'dHash peak memory : {np.mean(dhash_peaks):.0f} KB')\n",
]))
cells.append(code([
    "fig, ax = plt.subplots(figsize=(7, 5))\n",
    "means = [np.mean(find_peaks), np.mean(dhash_peaks)]\n",
    "stds  = [np.std(find_peaks),  np.std(dhash_peaks)]\n",
    "bars  = ax.bar(['FINDHasher_optimized', 'dHash (16×16)'],\n",
    "               means, color=['steelblue', 'darkorange'],\n",
    "               width=0.45, yerr=stds, capsize=6, edgecolor='white')\n",
    "for bar, m, s in zip(bars, means, stds):\n",
    "    ax.text(bar.get_x() + bar.get_width()/2, m+s+5,\n",
    "            f'{m:.0f} KB', ha='center', va='bottom', fontsize=10)\n",
    "ax.set_ylabel('Peak memory (KB)')\n",
    "ax.set_title('Peak Memory per Image (tracemalloc, 5 reps)', fontweight='bold')\n",
    "ax.grid(axis='y', alpha=0.3)\n",
    "plt.tight_layout()\n",
    "plt.savefig(OUTPUT_DIR / '04_memory.png', dpi=150, bbox_inches='tight')\n",
    "plt.show()\n",
]))

# ── 14  Scaling ───────────────────────────────────────────────────────────────
cells.append(md("---\n## 5. Scaling Analysis\n\nTotal wall-clock runtime and peak memory across dataset sizes N = 10, 50, 100, 500."))
cells.append(code([
    "SIZES = [10, 50, 100, 500]\n",
    "scaling = []\n",
    "for n in SIZES:\n",
    "    sample = random.sample(all_images, n)\n",
    "    # FINd\n",
    "    t0 = time.time()\n",
    "    for p in sample: find_hasher.fromFile(str(p))\n",
    "    find_t = time.time() - t0\n",
    "    # dHash\n",
    "    t0 = time.time()\n",
    "    for p in sample: dhash_fn(p)\n",
    "    dhash_t = time.time() - t0\n",
    "    scaling.append({'N': n, 'find_total_s': find_t, 'dhash_total_s': dhash_t,\n",
    "                    'find_per_img_ms': find_t/n*1000, 'dhash_per_img_ms': dhash_t/n*1000})\n",
    "    print(f'N={n:4d} | FINd {find_t:.2f}s ({find_t/n*1000:.1f}ms/img)  '\n",
    "          f'dHash {dhash_t:.2f}s ({dhash_t/n*1000:.1f}ms/img)')\n",
    "\n",
    "scale_df = pd.DataFrame(scaling)\n",
    "display(scale_df.round(3))\n",
]))
cells.append(code([
    "fig, axes = plt.subplots(1, 2, figsize=(12, 5))\n",
    "Ns = scale_df['N']\n",
    "\n",
    "axes[0].plot(Ns, scale_df['find_total_s'],  'o-', color='steelblue',  lw=2, label='FINDHasher_optimized')\n",
    "axes[0].plot(Ns, scale_df['dhash_total_s'], 'o-', color='darkorange', lw=2, label='dHash (16×16)')\n",
    "axes[0].set_xlabel('Number of images')\n",
    "axes[0].set_ylabel('Total wall-clock time (s)')\n",
    "axes[0].set_title('Total Runtime vs Dataset Size', fontweight='bold')\n",
    "axes[0].legend()\n",
    "axes[0].grid(alpha=0.3)\n",
    "\n",
    "axes[1].plot(Ns, scale_df['find_per_img_ms'],  'o-', color='steelblue',  lw=2, label='FINDHasher_optimized')\n",
    "axes[1].plot(Ns, scale_df['dhash_per_img_ms'], 'o-', color='darkorange', lw=2, label='dHash (16×16)')\n",
    "axes[1].set_xlabel('Number of images')\n",
    "axes[1].set_ylabel('Wall-clock per image (ms)')\n",
    "axes[1].set_title('Per-image Cost vs Dataset Size', fontweight='bold')\n",
    "axes[1].legend()\n",
    "axes[1].grid(alpha=0.3)\n",
    "\n",
    "fig.suptitle('Scaling Analysis', fontsize=13, fontweight='bold')\n",
    "plt.tight_layout()\n",
    "plt.savefig(OUTPUT_DIR / '04_scaling.png', dpi=150, bbox_inches='tight')\n",
    "plt.show()\n",
]))

# ── 15  Final summary ─────────────────────────────────────────────────────────
cells.append(md("---\n## 6. Summary"))
cells.append(code([
    "summary = pd.DataFrame({\n",
    "    'Metric': [\n",
    "        'AUC (ROC)', 'PR-AUC', 'EER', 'Best F1', 'Best threshold',\n",
    "        'Same-family mean dist', 'Diff-family mean dist', 'Gap (bits)',\n",
    "        'Wall-clock (ms/image)', 'CPU time (ms/image)', 'Peak memory (KB)',\n",
    "    ],\n",
    "    'FINDHasher_optimized': [\n",
    "        f'{find_auc:.4f}', f'{find_pr_auc:.4f}', f'{find_eer*100:.2f}%',\n",
    "        f'{find_f1[find_best]:.3f}', str(find_thr[find_best]),\n",
    "        f'{np.mean(find_same):.1f}', f'{np.mean(find_diff):.1f}',\n",
    "        f'{np.mean(find_diff)-np.mean(find_same):.1f}',\n",
    "        f'{np.mean(find_ms):.2f}', f'{np.mean(find_cpu):.2f}',\n",
    "        f'{np.mean(find_peaks):.0f}',\n",
    "    ],\n",
    "    'dHash (16×16)': [\n",
    "        f'{dhash_auc:.4f}', f'{dhash_pr_auc:.4f}', f'{dhash_eer*100:.2f}%',\n",
    "        f'{dhash_f1[dhash_best]:.3f}', str(dhash_thr[dhash_best]),\n",
    "        f'{np.mean(dhash_same):.1f}', f'{np.mean(dhash_diff):.1f}',\n",
    "        f'{np.mean(dhash_diff)-np.mean(dhash_same):.1f}',\n",
    "        f'{np.mean(dhash_ms):.2f}', f'{np.mean(dhash_cpu):.2f}',\n",
    "        f'{np.mean(dhash_peaks):.0f}',\n",
    "    ],\n",
    "})\n",
    "summary.set_index('Metric', inplace=True)\n",
    "display(summary)\n",
]))

nb = {
    "nbformat": 4, "nbformat_minor": 5,
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "version": "3.10.0"}
    },
    "cells": cells
}

out = "/Users/noha/Desktop/Hilary_term /DS in practice TA/FIN project/notebooks/04_comparison.ipynb"
with open(out, "w") as f:
    json.dump(nb, f, indent=1)
print(f"Written: {out}  ({len(cells)} cells)")
